# Generated by Django 5.0.3 on 2024-03-24 06:41

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projectsimage/')),
                ('createdAt', models.DateField(auto_now=True)),
                ('blog_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
    ]
