# Generated by Django 5.0.3 on 2024-03-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
